name: Build & deploy app

on:
  pull_request:
    paths:
      - "**/*.dockerfile"
      - "Dockerfile"
      - ".github/workflows/**/*"
  push:
    branches:
      - main

jobs:
  build_and_test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:  # Define outputs for this job
      short_sha: ${{ steps.get_short_sha.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Shortened GitHub SHA
        id: get_short_sha
        run: echo "::set-output name=short_sha::$(echo ${{ github.sha }} | cut -c1-7)"  # Shorten SHA using shell command

      - name: Build Docker Image
        run: docker build -t my-image:pr-${{ steps.get_short_sha.outputs.short_sha }} .

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: src/
          framework: terraform 

  build_upload_deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build_and_test  # This job depends on build_and_test
    env:
      SHORT_SHA: ${{ needs.build_and_test.outputs.short_sha }}  # Access the short SHA from the previous job
      REPOSITORY: my-ecr-repo
      IMAGE_TAG: ${{ needs.build_and_test.outputs.short_sha }}  # Use the shortened SHA as the image tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push to ECR
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:$IMAGE_TAG .
          docker push ${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:$IMAGE_TAG

      - name: Get ECS Cluster Name
        id: get_ecs_cluster_name
        run: echo "::set-output name=ecs_cluster_name::$(terraform output -raw ecs_cluster_name)"

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster ${{ steps.get_ecs_cluster_name.outputs.ecs_cluster_name }} --service my-service --force-new-deployment --region ${{ secrets.AWS_REGION }}
