name: Plan

on:
  pull_request:
    paths: ["infrastructure/**/*", ".github/workflows/**/*"]

permissions: 
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  actions: read
  
jobs:
  plan_staging:
    name: Terraform Plan (staging)
    uses: ./.github/workflows/_environment_plan.yml
    with:
      ENVIRONMENT: staging
      TF_WORKING_DIRECTORY: "infrastructure/"
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # plan_uat:
  #   name: Terraform Plan (uat)
  #   uses: ./.github/workflows/_environment_plan.yml
  #   with:
  #   secrets:

